before_script:
  - echo "Before script"
  - cd /var/www/recruitskill-web #your project path
building:
  stage: build
  script:
    - git init
    - git reset --hard
    - git pull master master
    - composer install
    - yarn install
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate --seed
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    - sudo chown -R deployer:www-data /var/www/recruitskill-web/
    - find /var/www/recruitskill-web -type f -exec chmod 664 {} \;
    - find /var/www/recruitskill-web -type d -exec chmod 775 {} \;
    - chgrp -R www-data storage bootstrap/cache
    - chmod -R ug+rwx storage bootstrap/cache



deploying:
  stage: deploy
  script:
    - echo "Deployed"
    - php artisan queue:restart #if you use queue
